import { Module } from '@nestjs/common';

import { GraphQLISODateTime, GraphQLModule } from '@nestjs/graphql';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MercuriusDriverConfig, MercuriusDriver } from '@nestjs/mercurius';
import { UserModule } from './resources/user/user.module';
import { SupporterModule } from './resources/supporter/supporter.module';

import path = require('path');

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql'),
      resolvers: { DateTime: GraphQLISODateTime },
      subscription: true,
      // graphiql: true,
    }),
    UserModule,
    SupporterModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
