import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'dist/apps/api/autogenerated-schema.gql',
  documents: ['apps/**/*gql.ts', 'libs/**/*gql.ts'],
  generates: {
    'libs/client/generated/graphql-types/src/lib/types.ts': {
      plugins: ['typescript'],
    },
    'lib/': {
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.gen.ts',
        baseTypesPath: '~@openluncher/client/generated/graphql-types',
      },
      plugins: ['typescript-operations', 'typescript-react-query'],
      config: {
        withHooks: true,
      },
    },
  },
};

export default config;
